### ISSUE TITLE
Call defresource dynamically

### ISSUE THREAD

**Issue by staab** [stephenmuss/argo#3]
Hey there, thanks for Argo! It's a great starting point for my new api. One thing I'd like to do is generate endpoints dynamically, based on a list of types and associated configuration objects. I'm sorta new to clojure, and so I'm not sure if there's a way to call macros with dynamic contents. My hunch is that there isn't. If that's the case, it would be awesome to have a function version of `defresource` or something. Here's essentially what I'm trying for, if `defresource` was a function:

```
(def config {:x {} :y {}})

(def types [:x :y])

(defapi v1 
  {:resources (vec (for [type types] (defresource (str type) (type config)))})
```

If there's a way to do this with the existing argo code, please let me know. Otherwise, I'll just have to do it manually, which isn't a big deal, but a bit repetitive. It's kinda annoying, because I want to mostly share the configuration objects between my endpoints, which makes things pretty verbose.

**Comment by stephenmuss** [comment]
Hi @staab, the problem here is that the macros `defapi` and `defresource` are expanded at compile time. Using them this way dynamically isn't really a possibility.

Without knowing more about your particular case it is hard to make suggestions. However I wonder whether you could potentially use something like [confd](https://github.com/kelseyhightower/confd) with your config which then creates a clojure file using `defapi` and `defresource` in such a way that the macros are expanded at compile time as expected.

I agree that it could be advantageous to allow creating resources with a function rather than a macro. I think as it stands at the moment it would require a reasonable amount of work to achieve this, but it could be worth looking in to.

**Comment by staab** [comment]
I'm not sure I want to go full configuration-management level at this point. To clarify my use case, I basically have a single edn file that contains a list of types and attributes that make up my domain model. I then read this file, and modify it to create a datomic schema and plumatic schemas. I had hoped to create my api using the same method. So if I went with confd for creating the api, there really wouldn't be much clojure left in my clojure project :stuck_out_tongue_winking_eye: 

At any rate, thanks for the quick response and the link!
